Shops = {
    "Kirsche": 1,
    "Apfel": 1,
    "Brombeere": 1,
    "Himbeere": 1,
    "Johannisbeere": 1,
    "Pflaume": 1,
    "Mirabelle": 1,
    "Walnuss": 1,
    "Birne": 1,
    "Olive": 1,
    "Kokosnuss": 1,
    "Palme": 1,
    "Traube": 1,
    "Zitrone": 1,
    "Orange": 1,
    "Engelstrompete": 1,
    "Fichtenzapfen": 1,
    "Fichte": 1,
    "Salat": 2,
    "Erdbeere": 2,
    "Tomate": 2,
    "Karotte": 2,
    "Aubergine": 2,
    "Zwiebel": 2,
    "Gurke": 2,
    "Radieschen": 2,
    "Paprika": 2,
    "Zucchini": 2,
    "Kürbis": 2,
    "Spargel": 2,
    "Kartoffel": 2,
    "Blumenkohl": 2,
    "Brokkoli": 2,
    "Heidelbeere": 2,
    "Knoblauch": 2,
    "Spinat": 2,
    "Rotkohl": 2,
    "Kaffee": 2,
    "Champignon": 2,
    "Basilikum": 2,
    "Kakao": 2,
    "Pilzgeflecht": 2,
    "Fliegenpilz": 2,
    "Buchsbaumsetzling": 2,
    "Buchsbaum": 2,
    "Steinpilz": 2,
    "Pfifferling": 2,
    "Speisemorchel": 2,
    "Kräuter-Seitling": 2,
    "Riesenträuschling": 2,
    "Brunnen 1": 3,
    "Brunnen 2": 3,
    "Dekosteine": 3,
    "Ente": 3,
    "Feuerstelle": 3,
    "Gartenzwerge": 3,
    "Gehweg 1": 3,
    "Gehweg 2": 3,
    "Gehweg 3,": 3,
    "Gehweg 4": 3,
    "Holzkugeln": 3,
    "kleines Boot": 3,
    "Pavillon 1": 3,
    "Pavillon 2": 3,
    "Pavillon 3,": 3,
    "Rutsche": 3,
    "Sandkasten": 3,
    "Schwanenpaar": 3,
    "Seerosenleuchte grün": 3,
    "Seerosenleuchte rosa": 3,
    "Seerosenleuchte rot": 3,
    "Seerosenleuchte türkis": 3,
    "Sitzecke": 3,
    "Steinkreis": 3,
    "Teich": 3,
    "Zengarten": 3,
    "Sonnenblume": 4,
    "Ringelblume": 4,
    "Rose": 4,
    "Lilie": 4,
    "Kornblume": 4,
    "Orchidee": 4,
    "Krokus": 4,
    "Gerbera": 4,
    "Lavendel": 4,
    "Tulpe": 4,
    "Nickende Distel": 4,
    "Gemeine Wegwarte": 4,
    "Sibirische Schwertlilie": 4,
    "Moorlilie": 4,
    "Seerose": 0,
    "Scheincalla": 0,
    "gelbe Teichrose": 0,
    "Wassersellerie": 0,
    "Wasserfeder": 0,
    "Krebsschere": 0,
    "Wasserknöterich": 0,
    "Rohrkolben": 0,
    "Sumpfdotterblume": 0,
    "Schwertlilie": 0,
    "Reis": 0,
    "Schilfsetzling": 0,
    "Schilf": 0
}